-- Harmic eCommerce Database Schema (Oracle SQL)

-- 1. Users Table
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    address VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Products Table
CREATE TABLE Products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    price NUMBER(10, 2) NOT NULL,
    stock_quantity NUMBER NOT NULL,
    category VARCHAR2(50)
);

-- 3. Orders Table
CREATE TABLE Orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMBER(10, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Pending'
);

-- Sample Data Insert for Products
INSERT INTO Products (name, description, price, stock_quantity, category) 
VALUES ('Fresh Red Apples', 'Sweet and crunchy organic apples', 250.00, 50, 'Fruits');

INSERT INTO Products (name, description, price, stock_quantity, category) 
VALUES ('Organic Spinach', 'Fresh green leafy spinach', 120.00, 30, 'Vegetables');

COMMIT;
